/* npm install --prefix tests; npx playwright install chromium; node tests/browser.cjs
   Optional PWA_BROWSER_PATH points to a compatible Chromium executable. */
const {chromium}=require('playwright'),fs=require('fs'),http=require('http'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),original=path.resolve(root,'tests/fixtures/spa-v1.html');
let serveNext=false,server,browser;const results=[];
const record=(name)=>{results.push(name);console.log('PASS',name)};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
function seed(n=100){const words={},aliases={},progress={};for(let i=0;i<n;i++){const word='word'+i,id='fr:tr:'+word;words[id]={id,word,normalized:word,targetLanguage:'fr',nativeLanguage:'tr',meaning:'meaning '+i,type:'noun',synonyms:[],antonyms:[],examples:[],expressions:[],createdAt:'2026-01-01',updatedAt:'2026-01-01'};aliases[id]=id;progress[id]={wordId:id,status:i%3===0?'memorized':i%3===1?'active':'archived',firstSeenAt:'2026-01-01',lastSeenAt:'2026-01-01',statusChangedAt:'2026-01-01',memorizedAt:null,archivedAt:i%3===2?'2026-01-01':null,archiveSourceStatus:i%3===2?'memorized':null};}return {schemaVersion:1,meta:{starterWordsInitialized:true},settings:{nativeLanguage:'tr',targetLanguage:'fr',difficulty:'A1-A2',dailyLimit:'10',theme:'system',fontSize:'normal'},words,aliases,progress,dailyUsage:{date:'2026-10-05',count:7}};}
async function main(){
 server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');let file=url.pathname==='/baseline.html'?original:path.join(root,url.pathname.replace(/^\/VocVoc\//,''));if(url.pathname==='/VocVoc/')file=path.join(root,'index.html');try{let data=fs.readFileSync(file);if(serveNext&&file.endsWith('sw.js'))data=Buffer.from(data.toString().replace("VERSION='1.0.0'","VERSION='1.0.1'"));if(serveNext&&file.endsWith('index.html'))data=Buffer.from(data.toString().replace('<title>VocVoc</title>','<title>VocVoc update test</title>'));res.setHeader('Cache-Control','no-store');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.webmanifest')?'application/manifest+json':file.endsWith('.png')?'image/png':'text/html');res.end(data);}catch(_){res.writeHead(404);res.end('missing');}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}`,url=base+'/VocVoc/';
 const launch={headless:true};if(process.env.PWA_BROWSER_PATH){launch.executablePath=process.env.PWA_BROWSER_PATH;launch.args=['--no-sandbox','--disable-dev-shm-usage','--disable-gpu'];}
 browser=await chromium.launch(launch);
 const errors=[];let context=await browser.newContext();await context.addInitScript(()=>document.addEventListener('DOMContentLoaded',()=>{window.bootRenderCounts={history:0,content:0};for(const [name,key] of [['renderHistory','history'],['renderAllLocal','content']]){const original=window[name];window[name]=(...args)=>{bootRenderCounts[key]++;return original(...args);};}}));let page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
 const ready=async(p=page)=>{await p.waitForFunction(()=>document.getElementById('storageBoot').hidden);await p.evaluate(()=>VocVocData.flush());};
 await page.goto(url);await ready();assert.equal(await page.evaluate(()=>VocVocData.getHistoryWords().length),3);assert.equal(await page.evaluate(()=>VocVocRegression.run().passed),true);assert.deepEqual(await page.evaluate(()=>bootRenderCounts),{history:1,content:1});assert.equal(await page.locator('#storageBoot').isVisible(),false);record('fresh initialization + 12 SPA guards + one main render pass');
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await ready();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);assert.equal((await page.evaluate(()=>VocVocPWARegression.run())).passed,true);record('online load/reload + worker activation + PWA guards');
 // Network failure path and UI must not mutate data.
 await page.evaluate(()=>VocVocSecrets.setApiKey('test-not-a-real-key'));
 const before=await page.evaluate(()=>JSON.stringify(VocVocData.getDb()));await context.setOffline(true);await page.evaluate(()=>fetchFromGeminiREST('network','test-not-a-real-key'));assert.equal(await page.evaluate(()=>JSON.stringify(VocVocData.getDb())),before);assert.equal(await page.locator('#loader').evaluate(el=>el.style.display),'none');assert.match(await page.locator('#appAlertLayer').innerText(),/İnternet/);record('offline Gemini: localized error, no data change, spinner clears');
 await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getHistoryWords().length),3);record('offline reload app shell + IndexedDB');
 await page.close();page=await context.newPage();await page.goto(url);await ready();record('offline cold tab start after installation');
 await context.setOffline(false);await context.close();
 // Same-origin migration is atomic, preserves source + secret separation, and is not repeated.
 context=await browser.newContext();page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const source=seed(1000);
 await context.addInitScript(db=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem('VOCVOC_DB_V1',JSON.stringify(db));localStorage.setItem('VOCVOC_SECRET_GEMINI_API_KEY','secret-test-value');sessionStorage.setItem('seeded','1');}},source);
 const started=Date.now();await page.goto(url);await ready();const startupMs=Date.now()-started;
 assert.deepEqual(await page.evaluate(()=>VocVocData.getDb()),source);assert.equal(await page.evaluate(()=>localStorage.getItem('VOCVOC_DB_V1')),JSON.stringify(source));assert(await page.evaluate(()=>localStorage.getItem('VOCVOC_MIGRATION_BACKUP_V1')));assert.equal(await page.evaluate(async()=> (await VocVocStorage.adapter.read()).migration.phase),'complete');record('1000-word migration exact match + retained localStorage + verified marker');
 await page.evaluate(()=>markMemorized('word1'));await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getWordProgress('word1').status),'memorized');record('memorize -> reload');
 const snapshot=await page.evaluate(()=>VocVocData.getWordProgress('word1'));
 await page.evaluate(async()=>{const state=await archiveWord('word1');showArchiveUndoToast(state);});assert.equal(await page.evaluate(()=>VocVocData.getWordProgress('word1').status),'archived');await page.evaluate(()=>undoLastArchive());await page.reload();await ready();assert.deepEqual(await page.evaluate(()=>VocVocData.getWordProgress('word1')),snapshot);record('memorized archive -> exact Undo -> reload');
 await page.evaluate(()=>removeMemorized('word1'));const active=await page.evaluate(()=>VocVocData.getWordProgress('word1'));await page.evaluate(async()=>showArchiveUndoToast(await archiveWord('word1')));await page.evaluate(()=>undoLastArchive());await page.reload();await ready();assert.deepEqual(await page.evaluate(()=>VocVocData.getWordProgress('word1')),active);record('active archive -> exact Undo -> reload');
 await page.evaluate(()=>archiveWord('word1'));await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getWordProgress('word1').status),'archived');await page.evaluate(()=>VocVocData.restoreArchived(['word1']));await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getWordProgress('word1').status),'memorized');record('archive persists + Restore keeps SPA memorized semantics');
 await page.evaluate(()=>VocVocData.deleteWords(['word2']));await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getWordByText('word2')),null);assert.equal(await page.evaluate(()=>localStorage.getItem('VOCVOC_DB_V1')),JSON.stringify(source));record('delete -> reload does not resurrect from retained migration source');
 await page.evaluate(()=>VocVocData.addDailyUsage(3));const daily=await page.evaluate(()=>VocVocData.getDailyUsage());await page.reload();await ready();assert.deepEqual(await page.evaluate(()=>VocVocData.getDailyUsage()),daily);record('dailyUsage persistence');
 await page.evaluate(()=>VocVocData.updateSettings({theme:'dark',fontSize:'large',difficulty:'B1-B2',dailyLimit:'20'}));await page.reload();await ready();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'dark');assert.equal(await page.evaluate(()=>document.documentElement.dataset.fontSize),'large');record('settings/theme/font persistence');
 await page.evaluate(async()=>{await VocVocData.saveAndTouch({word:'Écoute',meaning:'listen'},'écouter');await VocVocData.touchWord('écouter');});assert.equal(await page.evaluate(()=>VocVocData.getHistoryWords().filter(w=>w==='Écoute').length),1);assert.equal(await page.evaluate(()=>VocVocData.getWordByText('écouter').id),'fr:tr:ecoute');record('canonical alias + Unicode + no duplicate History');
 await page.evaluate(()=>{startQuiz();});const quiz=await page.evaluate(()=>quizSession.questions);assert.equal(quiz.length,10);assert.equal(new Set(quiz.map(q=>q.word)).size,10);assert.equal(await page.evaluate(()=>quizSession.questions.every(q=>VocVocData.getWordProgress(q.word).status==='active')),true);
 await page.evaluate(()=>startRecallQuiz());assert.equal(await page.evaluate(()=>quizSession.questions.length),10);assert.equal(await page.evaluate(()=>quizSession.questions.every(q=>VocVocData.getWordProgress(q.word).status==='memorized')),true);record('Test / Recall correct distinct 10-word pools; archived excluded');
 await page.evaluate(()=>{quizSession=null;renderAllLocal();startFlip();toggleFlipFilter('includeOther');});assert.equal(await page.evaluate(()=>flipSession.cards.every(c=>VocVocData.getWordProgress(c.word).status==='memorized')),true);await page.evaluate(()=>toggleFlipFilter('includeMemorized'));assert.equal(await page.evaluate(()=>flipSession),null);record('Flip filters + exit behavior');
 await page.evaluate(()=>{document.getElementById('historyFilterInput').value='word1';document.getElementById('historySort').value='az';renderHistory();});assert(await page.locator('.history-chip').count());assert.equal(await page.evaluate(()=>[...document.querySelectorAll('.history-chip')].every(el=>el.textContent.toLowerCase().includes('word1'))),true);record('History filter/sort');
 await page.evaluate(()=>toggleHistoryDetail('word1'));await pause(100);assert.equal(await page.evaluate(()=>getPageScroller().classList.contains('popup-scroll-locked')),true);await page.evaluate(()=>closeHistoryDetail());await pause(100);assert.equal(await page.evaluate(()=>getPageScroller().classList.contains('popup-scroll-locked')),false);record('popup background lock / release');
 // Explicit awaited mutations: failed commit cannot leak an optimistic memory update.
 const prior=await page.evaluate(()=>JSON.stringify(VocVocData.getDb()));assert.equal(await page.evaluate(async()=>{const adapter=VocVocStorage.adapter,write=adapter.write;adapter.write=()=>Promise.reject(new DOMException('full','QuotaExceededError'));try{await VocVocData.setStatus('word1','active');return false;}catch(_){return true;}finally{adapter.write=write;}}),true);assert.equal(await page.evaluate(()=>JSON.stringify(VocVocData.getDb())),prior);record('quota/write failure rollback retains committed runtime data');
 const backup=await page.evaluate(()=>VocVocData.export());assert(!JSON.stringify(backup).includes('secret-test-value'));assert.equal(backup.exportVersion,1);await page.evaluate(()=>VocVocData.setStatus('word1','active'));const preImport=await page.evaluate(()=>VocVocData.getDb());await page.evaluate(data=>VocVocData.import(data),backup);const imported=await page.evaluate(()=>VocVocData.getDb()),expected=Object.fromEntries(Object.entries(backup).filter(([k])=>!['exportVersion','exportedAt'].includes(k)));expected.meta.updatedAt=imported.meta.updatedAt;assert.deepEqual(imported,expected);const recovery=await page.evaluate(()=>VocVocStorage.adapter.recoveryBackup());assert.deepEqual(recovery,preImport);record('secret-free export + transactional restore + recovery snapshot');
 const valid=await page.evaluate(()=>JSON.stringify(VocVocData.getDb()));const invalidCases=[{...backup,schemaVersion:2},{...backup,progress:{bad:{wordId:'bad',status:'active'}}},{...backup,apiKey:'secret'},{...backup,exportVersion:9}];for(const invalid of invalidCases){assert.equal(await page.evaluate(async data=>{try{await VocVocData.import(data);return false;}catch(_){return true;}},invalid),true);}assert.equal(await page.evaluate(()=>JSON.stringify(VocVocData.getDb())),valid);record('invalid imports reject without changing data');
 // Second tab cannot overwrite a newer revision with a stale snapshot.
 const other=await context.newPage();await other.goto(url);await ready(other);await page.evaluate(()=>VocVocData.setStatus('word1','active'));assert.equal(await other.evaluate(async()=>{try{await VocVocData.setStatus('word1','memorized');return false;}catch(e){return e.storageCode==='conflict';}}),true);await other.close();record('multi-tab stale writer rejected');
 await context.setOffline(true);await page.reload();await ready();await page.evaluate(()=>{startQuiz();startRecallQuiz();quizSession=null;openModal();});await page.evaluate(()=>{closeModal();});await page.evaluate(()=>VocVocData.restoreArchived(['word5']));await page.evaluate(()=>VocVocData.deleteWords(['word8']));await page.evaluate(()=>VocVocData.updateSettings({theme:'light',fontSize:'xlarge'}));await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getWordByText('word8')),null);assert.equal(await page.evaluate(()=>VocVocData.getSettings().theme),'light');record('offline History/Test/Recall/Archive restore/delete/Settings + reload');
 await context.setOffline(false);
 // Model fallback, malformed response and connection error with real browser fetch interception.
 await page.route('https://generativelanguage.googleapis.com/**',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.evaluate(()=>fetchFromGeminiREST('unavailable','test'));assert.equal(await page.locator('#loader').evaluate(el=>el.style.display),'none');await page.unroute('https://generativelanguage.googleapis.com/**');
 let calls=0;await page.route('https://generativelanguage.googleapis.com/**',route=>{calls++;return route.fulfill({status:calls===1?503:200,contentType:'application/json',body:JSON.stringify(calls===1?{}:{candidates:[{content:{parts:[{text:JSON.stringify({word:'networkword',meaning:'network meaning'})}]}}]})});});await page.evaluate(()=>fetchFromGeminiREST('networkalias','test'));assert.equal(calls,2);assert.equal(await page.evaluate(()=>VocVocData.getWordByText('networkalias').word),'networkword');await page.unroute('https://generativelanguage.googleapis.com/**');record('network returns + unchanged Gemini fallback sequence');
 // Update is waiting until explicit user action; setting panel blocks update reload.
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await ready();await page.waitForFunction(()=>!!navigator.serviceWorker.controller);serveNext=true;await page.evaluate(()=>pwaRegistration.update());await page.waitForFunction(()=>!!pwaRegistration.waiting);await page.waitForSelector('#pwaUpdate');assert.equal(await page.title(),'VocVoc');await page.evaluate(()=>openModal());await page.locator('#pwaUpdate .ui-button').click();assert.equal(await page.title(),'VocVoc');await page.evaluate(()=>closeModal());const updateWords=await page.evaluate(()=>Object.keys(VocVocData.getDb().words).length);await Promise.all([page.waitForNavigation(),page.locator('#pwaUpdate .ui-button').click()]);await ready();assert.equal(await page.title(),'VocVoc update test');assert.equal(await page.evaluate(()=>Object.keys(VocVocData.getDb().words).length),updateWords);assert.equal(await page.evaluate(async()=>{const keys=await caches.keys();return keys.some(k=>k.endsWith('-1.0.1'))&&!keys.some(k=>k.endsWith('-1.0.0'));}),true);record('waiting update / busy protection / user refresh / obsolete cache cleanup');
 await context.setOffline(true);await page.reload();await ready();assert.equal(await page.title(),'VocVoc update test');record('new version offline reload');await context.setOffline(false);
 // Language reset is one atomic commit, preserving the configured pair across reload.
 await page.evaluate(()=>{requestLearningLanguageChange('targetLanguageDropdown','targetLanguage','de','German');return confirmLearningLanguageChange();});await page.reload();await ready();assert.equal(await page.evaluate(()=>VocVocData.getSettings().targetLanguage),'de');assert.equal(await page.evaluate(()=>Object.keys(VocVocData.getDb().words).length),0);record('language change + reset + reload atomic');
 await context.close();serveNext=false;
 // Interrupted migration after copy retries verification instead of duplicating.
 context=await browser.newContext();page=await context.newPage();await page.goto(base+'/baseline.html');await page.evaluate(async db=>{const req=indexedDB.open('VOCVOC_PWA',1);await new Promise((resolve,reject)=>{req.onupgradeneeded=()=>{req.result.createObjectStore('state');req.result.createObjectStore('control');};req.onerror=()=>reject(req.error);req.onsuccess=resolve;});const tx=req.result.transaction(['state','control'],'readwrite');tx.objectStore('state').put(db,'schema-v1');tx.objectStore('control').put(1,'revision');tx.objectStore('control').put({phase:'copied'},'migration');await new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onabort=reject;});req.result.close();localStorage.setItem('VOCVOC_DB_V1',JSON.stringify(db));},seed(120));await page.goto(url);await ready();assert.equal(await page.evaluate(()=>Object.keys(VocVocData.getDb().words).length),120);assert.equal(await page.evaluate(async()=> (await VocVocStorage.adapter.read()).migration.phase),'complete');record('interrupted migration copied phase safe retry');await context.close();
 // Invalid source must fail visibly without overwriting or deleting it.
 context=await browser.newContext();await context.addInitScript(()=>localStorage.setItem('VOCVOC_DB_V1','{broken'));page=await context.newPage();await page.goto(url);await page.waitForFunction(()=>!document.getElementById('storageRetry').hidden);assert.equal(await page.evaluate(()=>document.getElementById('storageBoot').hidden),false);assert.equal(await page.evaluate(()=>localStorage.getItem('VOCVOC_DB_V1')),'{broken');record('corrupt migration blocks bootstrap safely with recovery message');await context.close();
 // Responsive, theme and pointer smoke on actual Chromium, not mocked DOM.
 for(const width of [390,1280]){context=await browser.newContext({viewport:{width,height:844},hasTouch:width===390,isMobile:width===390});page=await context.newPage();await page.goto(url);await ready();for(const theme of ['light','dark']){await page.evaluate(t=>applyTheme(t),theme);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.evaluate(()=>toggleHistoryDetail('Bonjour'));await pause(60);const box=await page.locator('#historyDetails .history-detail-card').boundingBox();assert(box.x>=0&&box.x+box.width<=width+1);await page.evaluate(()=>closeHistoryDetail());}await context.close();}record('390px touch/mobile + desktop 1280px / light and dark popup bounds');
 // Search/Random/Daily use the unchanged AI contract, with durable async commits.
 context=await browser.newContext();page=await context.newPage();await page.goto(url);await ready();await page.evaluate(()=>VocVocSecrets.setApiKey('test'));
 await page.route('https://generativelanguage.googleapis.com/**',route=>{const prompt=JSON.parse(route.request().postData()).contents[0].parts[0].text;let data;if(prompt.includes('Choose ONE'))data={word:'randompwa'};else if(prompt.includes('"words"'))data={words:Array.from({length:10},(_,i)=>({word:'dailypwa'+i,meaning:'daily meaning '+i}))};else{const word=prompt.includes('randompwa')?'randompwa':prompt.includes('previewpwa')?'previewpwa':'searchpwa';data={word,meaning:'meaning '+word};}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify(data)}]}}]})});});
 await page.evaluate(()=>{document.getElementById('searchInput').value='query';return handleSearch();});assert(await page.evaluate(()=>VocVocData.getHistoryWords().includes('searchpwa')));await page.evaluate(()=>randomWord());assert(await page.evaluate(()=>VocVocData.getHistoryWords().includes('randompwa')));const dailyRevision=await page.evaluate(()=>VocVocStorage.adapter.revision);await page.evaluate(()=>addDailyWords());assert.equal(await page.evaluate(()=>VocVocData.getDailyUsage().count),10);assert.equal(await page.evaluate(()=>VocVocStorage.adapter.revision),dailyRevision+1);assert.equal(await page.locator('#contentArea .main-word-card').count(),10);
 await page.evaluate(()=>openRelatedWordPopup('previewpwa'));assert.equal(await page.evaluate(()=>VocVocData.getWordByText('previewpwa')),null);assert.equal(await page.locator('#relatedWordPopup .card-archive-btn').count(),0);await page.evaluate(()=>addRelatedWordToList('previewpwa'));assert(await page.evaluate(()=>VocVocData.getHistoryWords().includes('previewpwa')));await page.reload();await ready();assert(await page.evaluate(()=>VocVocData.getHistoryWords().includes('randompwa')));record('Search / Random / Daily atomic batch / Related preview-add / persistence');await context.close();
 // Actual pointer drags execute the async commit callbacks on every card family.
 context=await browser.newContext({viewport:{width:1000,height:850}});page=await context.newPage();await page.goto(url);await ready();
 const drag=async(selector,amount)=>{const box=await page.locator(selector).first().boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+amount,y+5,{steps:8});await page.mouse.up();};
 await page.evaluate(()=>toggleHistoryDetail('Bonjour'));await drag('#historyDetails .word-panel-scroll-body .section p',150);await page.waitForFunction(()=>VocVocData.getWordProgress('Bonjour').status==='memorized');
 await page.evaluate(()=>toggleHistoryDetail('Bonjour'));await drag('#historyDetails .word-panel-scroll-body .section p',-150);await page.waitForFunction(()=>VocVocData.getWordProgress('Bonjour').status==='active');record('History pointer swipe memorize/unmemorize persists');
 await page.evaluate(()=>openRelatedWordPopup('Merci'));await drag('#relatedWordPopup .word-panel-scroll-body .section p',150);await page.waitForFunction(()=>VocVocData.getWordProgress('Merci').status==='memorized');record('Related pointer swipe commits and closes');
 await page.evaluate(()=>{closeRelatedWordPopup();closeHistoryDetail();renderAllLocal();});await drag('#contentArea .main-word-card .main-word-toggle',150);await page.waitForFunction(()=>VocVocData.getWordProgress('Bonjour').status==='memorized');record('ContentArea pointer right swipe commits');
 await page.evaluate(()=>startFlip());const flipWord=await page.evaluate(()=>flipSession.cards[flipSession.index].word);const flipStatus=await page.evaluate(w=>VocVocData.getWordProgress(w).status,flipWord);await drag('#flipCard',flipStatus==='memorized'?-150:150);await page.waitForFunction(({w,status})=>VocVocData.getWordProgress(w).status!==status,{w:flipWord,status:flipStatus});await page.evaluate(()=>closeFlip());record('Flip pointer drag commits status');
 const pure=await page.evaluate(async()=>{const adapter=VocVocStorage.adapter,revision=adapter.revision,read=adapter.read;adapter.read=()=>{throw new Error('render read disk');};try{for(let i=0;i<100;i++){renderWordCard({word:'Je',meaning:'meaning'});VocVocData.getWordByText('Je');}return revision===adapter.revision;}finally{adapter.read=read;}});assert(pure);record('render/getter hot paths do not write/read IndexedDB');
 await page.evaluate(()=>openModal());await page.locator('#backupLabel').click();const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#exportDataBtn').click()]);const exportPath=await download.path();const exported=JSON.parse(fs.readFileSync(exportPath,'utf8'));assert.equal(exported.exportVersion,1);assert(!JSON.stringify(exported).includes('GEMINI_API_KEY'));
 const restoreWord=exported.words[Object.keys(exported.words)[0]].word;await page.evaluate(w=>VocVocData.deleteWords([w]),restoreWord);page.once('dialog',dialog=>dialog.accept());await Promise.all([page.waitForNavigation(),page.locator('#importDataFile').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))})]);await ready();assert(await page.evaluate(w=>!!VocVocData.getWordByText(w),restoreWord));record('Settings JSON download / confirmed file restore / reload');await context.close();
 // Baseline layout geometry is unchanged at zero safe-area inset.
 for(const width of [390,1280]){const geometries=[];for(const baseline of [true,false]){context=await browser.newContext({viewport:{width,height:844}});page=await context.newPage();await page.goto(baseline?base+'/baseline.html':url);if(!baseline)await ready();geometries.push(await page.evaluate(()=>Object.fromEntries(['.container','#topChrome','#contentArea','.main-word-card','#historyArea'].map(selector=>{const el=document.querySelector(selector),rect=el.getBoundingClientRect(),css=getComputedStyle(el);return [selector,{x:rect.x,y:rect.y,width:rect.width,height:rect.height,font:css.fontSize,overflow:css.overflow}];}))));await context.close();}assert.deepEqual(geometries[1],geometries[0]);}record('SPA baseline geometry unchanged: mobile + desktop');
 assert.deepEqual(errors,[]);record('no browser JavaScript errors');
 console.log(JSON.stringify({passed:results.length,startup1000ms:startupMs,results},null,2));fs.writeFileSync(path.join(root,'tests','browser-results.json'),JSON.stringify({passed:results.length,startup1000ms:startupMs,results},null,2));
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();server?.close();});
