const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),{IDBFactory}=require('fake-indexeddb');
const ctx={indexedDB:new IDBFactory(),structuredClone,setTimeout,clearTimeout,CustomEvent:class{},dispatchEvent(){}};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(require('path').join(__dirname,'../storage.js'),'utf8'),ctx);const storage=vm.runInContext('VocVocStorage',ctx);
const fresh=()=>({schemaVersion:1,meta:{},settings:{nativeLanguage:'tr',targetLanguage:'fr',difficulty:'A1-A2',dailyLimit:'10',theme:'system',fontSize:'normal'},words:{},aliases:{},progress:{},dailyUsage:{date:null,count:0}});
(async()=>{
 const adapter=storage.adapter;let builds=0;await adapter.initialize(()=>{builds++;return fresh();});assert.equal(builds,1);assert.equal((await adapter.read()).migration.phase,'complete');
 let db=fresh();db.meta.test='before';await adapter.write(db);const rev=adapter.revision;
 await assert.rejects(adapter.transaction('readwrite',(tx,set,abort)=>{tx.objectStore('state').put({...db,meta:{test:'aborted'}},'schema-v1');abort(new Error('forced abort'));}),/forced abort/);assert.equal((await adapter.read()).db.meta.test,'before');assert.equal((await adapter.read()).revision,rev);
 adapter.close();await adapter.initialize(()=>{throw new Error('migration must not repeat');});assert.equal((await adapter.read()).db.meta.test,'before');
 const second=new storage.IndexedDBAdapter();await second.initialize(()=>fresh());await adapter.write({...db,meta:{test:'new'}});await assert.rejects(second.write({...db,meta:{test:'stale'}}),e=>e.storageCode==='conflict');assert.equal((await adapter.read()).db.meta.test,'new');
 const recoveryBefore=(await adapter.read()).db;await adapter.write({...db,meta:{test:'imported'}},{backup:true});assert.deepEqual(await adapter.recoveryBackup(),recoveryBefore);
 assert.throws(()=>storage.validate({...fresh(),schemaVersion:2}));assert.throws(()=>storage.validate({...fresh(),apiKey:'no'}));assert.throws(()=>storage.validate({...fresh(),words:JSON.parse('{"__proto__":{}}')}));
 const w={id:'fr:tr:secret',word:'secret',normalized:'secret',targetLanguage:'fr',nativeLanguage:'tr'};const wordDb=fresh();wordDb.words[w.id]=w;wordDb.aliases[w.id]=w.id;storage.validate(wordDb); // valid vocabulary is not mistaken for a secret field
 adapter.close();second.close();ctx.indexedDB=new IDBFactory();const interrupted=new storage.IndexedDBAdapter();await interrupted.open();const transaction=interrupted.transaction.bind(interrupted);interrupted.transaction=(mode,work)=>transaction(mode,mode==='readwrite'?(tx,set,abort)=>{work(tx,set,abort);abort(new Error('migration interrupted'));}:work);await assert.rejects(interrupted.initialize(()=>fresh()),/migration interrupted/);interrupted.transaction=transaction;assert.equal((await interrupted.read()).db,undefined);assert.equal((await interrupted.read()).migration,undefined);await interrupted.initialize(()=>fresh());assert.equal((await interrupted.read()).migration.phase,'complete');interrupted.close();
 ctx.indexedDB=new IDBFactory();const raceA=new storage.IndexedDBAdapter(),raceB=new storage.IndexedDBAdapter();const [a,b]=await Promise.all([raceA.initialize(()=>({...fresh(),meta:{tab:'a'}})),raceB.initialize(()=>({...fresh(),meta:{tab:'b'}}))]);assert.deepEqual(a,b);assert.equal((await raceA.read()).migration.phase,'complete');raceA.close();raceB.close();
 ctx.indexedDB=null;const unavailable=new storage.IndexedDBAdapter();await assert.rejects(unavailable.open(),e=>e.storageCode==='unavailable');
 adapter.close();second.close();console.log('PASS storage: transaction abort, durable readback, idempotency, optimistic revision, import recovery, validation, unavailable DB');
})().catch(e=>{console.error(e);process.exitCode=1});
