const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),cp=require('child_process');const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const file of ['storage.js','pwa.js','sw.js','tools/export-from-spa.js','tests/browser.cjs','tests/storage.cjs','tests/validate.cjs'])cp.execFileSync(process.execPath,['--check',path.join(root,file)]);
const inline=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(x=>x[1]).join('\n');new vm.Script(inline);
for(const m of html.matchAll(/(?:src|href)="(\.\/[^"]+)"/g))assert(fs.existsSync(path.join(root,m[1])),m[1]);const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.webmanifest'),'utf8'));assert.equal(manifest.display,'standalone');assert.equal(manifest.scope,'./');assert.equal(manifest.start_url,'./');for(const icon of manifest.icons){assert(fs.existsSync(path.join(root,icon.src)));const bytes=fs.readFileSync(path.join(root,icon.src));const [w,h]=icon.sizes.split('x').map(Number);assert.equal(bytes.readUInt32BE(16),w);assert.equal(bytes.readUInt32BE(20),h);}
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8'),assets=JSON.parse(sw.match(/const ASSETS=(\[[^;]+\]);/)[1].replaceAll("'",'"'));for(const asset of assets)assert(fs.existsSync(path.join(root,asset==='./'?'index.html':asset)));
assert.equal((html+fs.readFileSync(path.join(root,'pwa.js'),'utf8')).match(/serviceWorker\.register\(/g).length,1);assert(!html.includes('indexedDB.'));assert(!sw.includes('generativelanguage.googleapis.com'));assert(sw.includes("req.method!=='GET'||url.origin!==scope.origin"));assert(sw.includes('key!==CACHE'));assert(!/skipWaiting\(\)/.test(sw.slice(sw.indexOf("self.addEventListener('install'"),sw.indexOf("self.addEventListener('activate'"))));
assert(!/(?:swipe-armed|main-swipe-archive)\s*\{/.test(html));assert(!/max-height:\s*260px\s*[;!]/.test(html));assert(!/function renderWordCard[\s\S]*?(?:VocVocData\.(?:saveWord|setStatus|touchWord))/.test(html.split('function renderWordCard')[1]?.split('let archiveSelection')[0]||''));
// Real service worker handlers with synthetic requests: AI never calls respondWith.
const listeners={},deleted=[],current=sw.match(/const VERSION='([^']+)'/)[1];const worker={URL,Request,Promise,self:{registration:{scope:'https://example.org/VocVoc/'},clients:{claim:async()=>{}},addEventListener:(name,cb)=>listeners[name]=cb,skipWaiting:async()=>{}},caches:{keys:async()=>['vocvoc-shell-%2FVocVoc%2F-old','vocvoc-shell-%2FVocVoc%2F-'+current,'other-cache'],delete:async key=>deleted.push(key),open:async()=>({addAll:async()=>{},match:async()=>({shell:true})})},fetch:async()=>({network:true})};vm.createContext(worker);vm.runInContext(sw,worker);
let intercepted=0;listeners.fetch({request:new Request('https://generativelanguage.googleapis.com/v1',{method:'POST'}),respondWith(){intercepted++}});listeners.fetch({request:new Request('https://example.org/private'),respondWith(){intercepted++}});assert.equal(intercepted,0);let activation;listeners.activate({waitUntil:p=>activation=p});activation.then(()=>{assert.deepEqual(deleted,['vocvoc-shell-%2FVocVoc%2F-old']);console.log('PASS all JS syntax, manifest/icons/references, one registration, SPA/PWA static guards, SW external bypass + owned cache cleanup');}).catch(e=>{console.error(e);process.exitCode=1});
